### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by legoktm** [mustangostang/spyc#38]
Hi! It's been nearly 2 years since the last release, could you tag a new one? 

I'm asking because we're currently using a bundled copy of this library on Wikimedia projects, and we'd like to bring it in with composer instead, which would require a newer release. Our ticket is [here](https://phabricator.wikimedia.org/T75945). Thanks!

**Comment by bd808** [comment]
ping?

**Comment by eteubert** [comment]
👍

**Comment by jackmcdade** [comment]
👍

**Comment by jackmcdade** [comment]
Done!
