### ISSUE TITLE
weird issue: ssh key not parsed correctly

### ISSUE THREAD

**Issue by iahim** [mustangostang/spyc#43]
i have a yaml file where i store some ssh pub keys:
```
sshkeys:
  - ssh-rsa A---LOOOONG-SSH-KEY---rxs=  some comment
```
when reading the yaml i get the correct value
```
[sshkeys] => Array
        (
            [0] => ssh-rsa A---LOOOONG-SSH-KEY---rxs=  some comment
```
BUT when writing that value back to the yaml file....i get this:

```
sshkeys:
  - >
    ssh-rsa
    A--LONG-KEY=
    comment root key
```
THE result is split into 4 lines ... with the weird ">"  and the key on 3 lines instead of one.

Any idea?
Thank you kindly

**Comment by IngwiePhoenix** [comment]
When you parse the output file again, do you get the correct key? Otherwise, the length of the string might just be wrapped down. So instead of one line of 80 characters, the printer generates 2 lines of 40 characters instead.

**Comment by iahim** [comment]
@IngwiePhoenix  Thanks for your reply.
It seems that you are right, that is somehow wrapped... but that is a major issue to me.. because that yaml file is being read by another app as well... and this wrapping just breaks the program.  Is there a way to disable this wrapping... and keep a long line?

Thanks in advance,
Mike

**Comment by iahim** [comment]
@IngwiePhoenix  i think i have found the solution. 

Spyc::YAMLDump($array, $indent = false, $wordwrap = 0, $no_opening_dashes = false);

the value 0 for wordwrap makes it work.
