### ISSUE TITLE
Add class_exists() check

### ISSUE THREAD

**Issue by tatemz** [mustangostang/spyc#48]
I have ran into an issue within a few projects (specifically those involving wp-cli) where I am running into pre-defined class conflicts...

[Consider taking the approach done by wp-cli.](https://github.com/wp-cli/wp-cli/blob/master/php/Spyc.php#L35)

    if ( ! class_exists( 'Spyc' ) ) {
        class Spyc {
        ...
        }
    }

**Comment by realgeek** [comment]
+1 Needed for auto updates with wp-cli.

**Comment by eteubert** [comment]
+1 Needed for WordPress plugin compatibilities. Right now I have to resort to a [rather ugly hack](https://github.com/podlove/podlove-publisher/blob/release-2-4-0/bin/fix_spyc_loading.php) to achieve the same effect.

**Comment by tatemz** [comment]
Thanks! 👍 

Yay for supported repos! 💯
