### ISSUE TITLE
YAML@1.2?

### ISSUE THREAD

**Issue by IngwiePhoenix** [mustangostang/spyc#51]
Previously, my project used INI files. But the more they have, the more unstructured they feel. So I wanted to change to using YAML.

First time I searched, I came to https://www.npmjs.com/package/js-yaml - which does 1.2. That would satisfy the NodeJS part of the project. But the PHP half?

Spyc is said to only do 1.0. I wanted to ask;

- What is the key difference between 1.0 and 1.2?
- Will Spyc eventually do 1.2?

Kind regards, Ingwie.

**Comment by funkytaco** [comment]
I think this project is dead, so probably not.

**Comment by jackmcdade** [comment]
@IngwiePhoenix if you want YAML 1.2 i would recommend <https://github.com/symfony/yaml>.

**Comment by jackmcdade** [comment]
@IngwiePhoenix as for the difference...

1.0 is pretty loose while 1.2 is a lot stricter. The biggest differences involve syntax formatting and type casting.

In 1.0 you can do this:
```
# Fine in 1.0
title:Happy place
title: Other happy place
```

That would throw an error in 1.2. You MUST have a `space` following the colon.

```
# 1.2
title: Happy place
```

That's a small thing. Here are more things:

```
# All of these evaluate as a strict boolean `true`
foo: true
foo: 1
foo: y
foo: yes

# All of these evaluate as a strict boolean `false`
bar: false
bar: 0
bar: n
bar: no
```

In 1.2 those keywords are just:
```
foo: true
bar: false
```

That's not all, but that's a good idea of the types of changes. You can explore the specs here:

- <http://yaml.org/spec/1.0/>
- <http://www.yaml.org/spec/1.2/spec.html>
