### ISSUE TITLE
Please do a release?

### ISSUE THREAD

**Issue by edalzell** [mustangostang/spyc#55]
Issue #41 was fixed in a fork and merged into master a while ago, but there has been no new release to incorporate it.

Can you please do a release so other packages can pick up the fix?

**Comment by jeremydouglas** [comment]
A release would be much appreciated and fix some issues I'm dealing with.

**Comment by fredemmott** [comment]
Old request here with no response: https://github.com/mustangostang/spyc/issues/38

**Comment by jackmcdade** [comment]
Done!
