### ISSUE TITLE
Unexpected retag of 0.6.3? and ClassNotFound now

### ISSUE THREAD

**Issue by alexander-schranz** [mustangostang/spyc#90]
I currently not sure but it seems like the 0.6.3 was retagged today.

![Bildschirmfoto 2024-03-07 um 16 48 23](https://github.com/mustangostang/spyc/assets/1698337/5f9a42dc-c893-4820-b6e9-bbe203ae5c8d)

Since then unexpected errors happening `ClassNotFoundError`:

<img width="865" alt="Bildschirmfoto 2024-03-07 um 16 51 09" src="https://github.com/mustangostang/spyc/assets/1698337/eb756828-2ede-4548-adb5-74574adff343">

It feels really strange not sure if really something was retagged with another commit id today or what is going on with this library.

**Comment by roborourke** [comment]
Composer seems to be ignoring the `autoload` portion of the `composer.json` so Spyc.php is not included in `autoload_files.php`. Not sure if it's an issue with this repo or packagist, or composer itself. The commit hash in my `composer.lock` looks right, and I can't see any differences between 0.6.3 on this repo and the version that's in my `vendor` folder.

**Comment by ramyelsabahy** [comment]
Also happening here, laravel 9 & php 8.1

**Comment by roborourke** [comment]
I emailed Jordi, it was a bug in packagist that lead to some metadata getting mangled, all affected packages have been fixed including this one.

nothing to do with this repo specifically.

**Comment by alexander-schranz** [comment]
Thank you! Tag also has now the correct date again:

![Bildschirmfoto 2024-03-08 um 10 18 09](https://github.com/mustangostang/spyc/assets/1698337/58e486f5-6f52-46b2-83e8-40845631571e)
